### PR TITLE
Add missing extensions

### PR DESCRIPTION
**Pull request by kghbln**
* Create Page
* Page Approvals
* Persistent Page Identifiers

### CODE REVIEW

**Comment by kghbln** [comment]
@hexmode Probably fails since not submodule was added. However, I have no clue how to do so. Any guidance is appreciated.

**Comment by kghbln** [comment]
Thanks a bunch for your help. Still failing due to unmet policy. It looks like Pickle is at fault. :|

**Comment by hexmode** [comment]
No, the policy is telling you that you didn't put `PersistentPageIdentifiers` in the right order.  It should go after `PeriodicRelatedChanges`.  This should really be an automated fix, but if you could update your branch, I'd appreciate it.

**Comment by kghbln** [comment]
That explains why I could not pickle the extensions into this repo—senior moments. Thanks for your help. Much appreciated!

**Pull request merged**
