### PR TITLE
Add femiwiki extension and skin

### PR DESCRIPTION
**Pull request by revi**
* Extension GPL2.0+
* Skin CC0

### CODE REVIEW

**Comment by hexmode** [comment]
Thank you!

**Comment by hexmode** [comment]
Could you explain what Sanctions does?

**Comment by revi** [comment]
I'm not the original dev of that extension (I'm not affiliated with them) but they have bit of docs on https://www.mediawiki.org/wiki/Extension:Sanctions

**Comment by hexmode** [comment]
Ah, sorry.  I saw that, but it didn't really clear things up.  It looks like it might be a way to block people from editing by consensus/voting which was an interesting possibility.

**Comment by revi** [comment]
From the working example of Femiwiki, it looked like they have automated the process of handling block/renaming offensive usernames - when certain active community members approve it.

**Pull request merged**
