### PR TITLE
Cleanup of submodules

### LINKED ISSUE #38: Remove extensions that are also in mediawiki-extensions
The following extensions are listed both here and in https://gerrit.wikimedia.org/g/mediawiki/extensions

Assuming their canonical versions are the Gerrit-hosted ones, they should probably be removed from nonwmf-extensions.

- [ ] ArticleIndex
- [ ] CloneDiff
- [ ] DocBookExport
- [ ] Figures
- [x] GlobalContribs
- [ ] Loops
- [x] MediaWikiAuth
- [ ] PageAuthors
- [x] Shariff-Mediawiki — #39
- [ ] Tabber
- [ ] UserSnoop
- [x] VEForAll — #39
- [x] WikiSEO — #39

### PR DESCRIPTION
**Pull request by kizule**
Submodules which already exists on Gerrit, or are marked read-only, are removed from this list.

Fixes #38

### CODE REVIEW

**Comment by kizule** [comment]
@hexmode Can you take a look into this please? This should be good to go. :)

**Comment by hexmode** [comment]
Could you update your PR so that DPL3 points to the [HydraWiki repository on GitLab](https://gitlab.com/hydrawiki/extensions/DynamicPageList)? Alternatively, since the [MediaWiki page for the extension](https://www.mediawiki.org/wiki/Extension:DynamicPageList3) points to the repo you're removing, add it back.

I'm not sure why you're removing it since I can find it still being used on several wikis even though it hasn't been updated in a few years.

**Comment by kizule** [comment]
I thinked that it is better to have updated repository. But I'll bring it back.

**Comment by hexmode** [comment]
I'm sorry, this is my fault: I only looked at your diff and didn't see that the github-based DPL3 was already in the repo.  So you were right when you said

> I thinked that it is better to have updated repository.

I just didn't understand that it was already there because the list was out of order.

Please undo the recent changes or force-push [b4f2dbd](https://github.com/MWStake/nonwmf-extensions/pull/49/commits/b4f2dbd49d2197ada20164d16bfdc5d3cb066e1e) to your branch.

Thank you for your help and patience with me.

**Comment by kizule** [comment]
> I'm sorry, this is my fault: I only looked at your diff and didn't see that the github-based DPL3 was already in the repo. So you were right when you said
> 
> > I thinked that it is better to have updated repository.
> 
> I just didn't understand that it was already there because the list was out of order.
> 
> Please undo the recent changes or force-push [b4f2dbd](https://github.com/MWStake/nonwmf-extensions/pull/49/commits/b4f2dbd49d2197ada20164d16bfdc5d3cb066e1e) to your branch.
> 
> Thank you for your help and patience with me.

No problem, you're welcome. Done. :)

**Comment by kizule** [comment]
This will need "Squash and merge". ;) https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request

**Comment by kizule** [comment]
Thank you! :)

**Pull request merged**
