### PR TITLE
Add missing extensions, tweak existing extensions

### PR DESCRIPTION
**Pull request by kghbln**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Note to reviewer: both @kghbln and myself could perhaps be given write access to this repo. Think we've been around long enough to establish we will not add too many cat pictures and self merge those :)

**Comment by kghbln** [comment]
@hexmode Conflict caused by the recent merge was resolved.

**Comment by kizule** [comment]
+1 :)

**Comment by kizule** [comment]
Huh, fixing failure now...

**Pull request merged**
